NumPy arrays are at the core of numerical computing in Python. They're more efficient than regular Python lists, especially for large datasets, because they offer faster processing and require less memory.

1. Getting Started with NumPy

First, you'll need to import NumPy:

In [1]:
import numpy as np

2. Creating NumPy Arrays

From Lists:

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


Multi-dimensional Arrays (Matrices):

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[[1 2 3]
 [4 5 6]]


Predefined Arrays with Zeros: Creates an array filled with zeros.

In [4]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ones: Creates an array filled with ones.

In [5]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Range of Numbers:

In [6]:
arr_range = np.arange(0, 10, 2)  # Start at 0, end before 10, step of 2
arr_range

array([0, 2, 4, 6, 8])

Evenly Spaced Numbers:

In [7]:
lin_space = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
lin_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

3. Array Operations:Element-wise Arithmetic:

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)  # [5 7 9]

# Multiplication
print(arr1 * arr2)  # [4 10 18]


[5 7 9]
[ 4 10 18]


Broadcasting:

In [9]:
arr = np.array([1, 2, 3])
print(arr + 5)  # [6 7 8]  (adds 5 to every element)


[6 7 8]


4. Array Indexing & Slicing

Indexing:

In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])  # 20


20


Slicing:

In [11]:
print(arr[1:4])  # [20 30 40]


[20 30 40]


2D Array Indexing:

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 2])  # 6 (2nd row, 3rd column)


3


5. Useful NumPy Functions:Sum, Mean, Max:

In [16]:
print(arr.sum())   # Sum of all elements
print(arr.mean())  # Mean of elements
print(arr.max())   # Maximum value


150
30.0
50


Reshaping Arrays:

In [18]:
reshaped = np.arange(9).reshape(3, 3)
print(reshaped)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Transposing Arrays:

In [19]:
transposed = reshaped.T
print(transposed)


[[0 3 6]
 [1 4 7]
 [2 5 8]]


6. Boolean Indexing & Filtering

In [21]:
arr = np.array([1, 2, 3, 4, 5])

# Filter values greater than 3
filtered = arr[arr > 3]
print(filtered)  # [4 5]


[4 5]
